 package projudp3;
import java.io.IOException;
import java.io.PrintStream;
import java.net.Socket;
public class Cliente1 extends javax.swing.JFrame {
    private static Socket cliente; //Variavel de conexão (cliente) que vai se comunicar com o servidor
    
    public Cliente1() {
        initComponents();
        iniciaCLiente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menssagem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menssagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menssagemActionPerformed(evt);
            }
        });
        getContentPane().add(menssagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 170, -1));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 234, 24));

        setSize(new java.awt.Dimension(482, 238));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menssagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menssagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menssagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviamensagem(menssagem.getText()); //Esse é a parte do botão, que ao ser clicado vai "acionar" o metodo "enviamensagem" para envia-lá e em seguida imprimir a msg de confirmação
        resultado.setText("Mensagem enviada com sucesso!!"); // A menssagem sera exibida dentro do label nomeado como "resultado" na interface grafica.
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente1().setVisible(true);
            }
        });
    }
    private static void iniciaCLiente(){// esse metodo foi criado no formato estatico pq depois ele vai ser chamado dentro da main, que tbm é statica
        try {
            cliente = new Socket("127.0.0.1",3334); // tinhamos declarado o metodo, agora estamos instaciando ele e declarando o IP e a Porta, nele.
            System.out.println("Teste, tudo certo!");
        } catch (IOException ex) {
            System.out.println("Erro, não foi possivel conectar ao servidor");
        }
    }
    
    private static void enviamensagem(String msg){ 
        PrintStream saida;
        try {
            saida = new PrintStream(cliente.getOutputStream()); // "PrintStream" é o tipo de objeto utilizado para enviar mensagens/ "getOutputStream()" pega a saida, "cliente" contem os dados do destinatario "ip e pota"
            saida.println(msg);
        } catch (IOException ex) {
            System.out.println("Erro ao enviar menssagem!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField menssagem;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
